name: Build Server
run-name: Build pit-common-lib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven and push to artifactory
        run: |
          export MAVEN_OPTS="-Xmx3072m -XX:MaxMetaspaceSize=512m"
          export NODE_OPTIONS="--max-old-space-size=4096"
          export GH_PKG_MAVEN_URL=${{ vars.GH_PKG_MAVEN_URL }}
          mvn --settings=settings.xml --batch-mode --update-snapshots -f server/pit-common-lib/pom.xml -Drepo.login=${{ secrets.IDIR_AS_EMAIL }} -Drepo.password=${{ secrets.IDIR_PASSWORD }} -DghPkgRepo.login=${{ github.actor }} -DghPkgRepo.password=${{ secrets.GITHUB_TOKEN }} deploy
