name: Build and publish client\pit-core-lib package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      # for the ng librabry name 
      MICROSERVICE_NAME:
        required: true
        type: choice
        options:
          - pit-common-core-lib
          # add the second library pit-common-application-lib as an option here once it's ready

env:
  NPMRC: ${{ secrets.NPMRC }} 


jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Extract version number
        id: getVersion
        run: echo "VERSION_NUMBER=$(grep -Po '"version"\s*:\s*"\K[^"]+' "client/${{ inputs.MICROSERVICE_NAME }}/angular/package.json")" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          # registry-url: https://npm.pkg.github.com  
          # scope: '@bcgov'

      - name: Add .npmrc file
        run: echo -e $NPMRC > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies for Angular project
        run: |
          cd client/${{ inputs.MICROSERVICE_NAME }}/angular
          npm clean-install
        # we can specify the gov't artifactory here if needed: npm clean-install --registry=https://bwa.nrs.gov.bc.ca/int/artifactory/api/npm/nrs-virtual-npm/

      - name: Build Angular library
        run: |
          cd client/${{ inputs.MICROSERVICE_NAME }}/angular
          npm run build
          export VERSION_NUMBER=${{ steps.getVersion.outputs.VERSION_NUMBER }}
          export DIST_NAME="dist/${{ inputs.MICROSERVICE_NAME }}"
          tar -cvzf ${{ inputs.MICROSERVICE_NAME }}-$VERSION_NUMBER.tgz $DIST_NAME

      - name: Publish package
        run: npm publish client/${{ inputs.MICROSERVICE_NAME }}-$VERSION_NUMBER.tgz
        # I have specified the publishConfig option in package json but 
        # we can point npm to use the github package registry here if the above doesn't work: 
        # npm publish --@bcgov:registry=https://npm.pkg.github.com
        # we might need to include the run number when publishing to the github registry: -$VERSION_NUMBER.${{ github.run_number }}.tgz
        # because npm doesn't handle snapshot versions as gracefully as maven
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
